modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="warpstonemod"
version="1.0"
displayName="Warpstone"
displayURL="https://www.curseforge.com/minecraft/mc-mods/warpstone"
logoFile="warpstone_title.png"
authors="Ya Boi Lenin"
description='''Warpstone is a mod about eating strange gems to mutate yourself in strange and powerful ways'''

[[dependencies.warpstonemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.warpstonemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
